### ISSUE TITLE
Plans on adding PDF?

### ISSUE THREAD

**Issue by DiegoRBaquero** [mikeal/snapkit#3]
Hey @mikeal ,

Are you planning on adding PDF support? Would you accept contributions?

I searched through npm packages for HTML -> PNG/PDF and found yours, which is new, awesome! Wouldn't want to repeat and create another module.

Let me know :)

**Comment by mikeal** [comment]
would love it, probably just add "pdf" to the accepted types in the `type` option and then check it before we take the screenshot to swap out the method.

**Comment by mikeal** [comment]
FYI, here's the puppeteer docs for getting pdfs https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions
